### ISSUE TITLE
Question - What are the requirements to mark a trace with error=yes?

### ISSUE THREAD

**Issue by anghelyi** [opensearch-project/dashboards-observability#771]
Hello! Sorry for my question but I was not able to find exact answer anywhere about what qualifies a trace to be marked as erroneous. I've been playing with OpenSearch+OpenTelemetry agents on and off for a few weeks and I find the traces' error rate very low compared to what I'm used to see in metrics. For me it seems that having an erroneous span in the trace does not automatically mark the trace with error. But sometimes it does, so that's why I'm confused. As I see, and correct me if I'm wrong, if one of the spans in the trace have an exception, that marks the trace with error. What are the other conditions? Is it configurable somewhere? Can you point me into the right direction where can I more information about it?
Thanks in advance!

**Comment by YANG-DB** [comment]
Hi @anghelyi 
Thanks for bringing this to our attention - can u give some concrete samples that we can look deeper into ?

**Comment by anghelyi** [comment]
Hi!
Sorry for the late reply, I dug out two examples. Unfortunately I'm not allowed to share the full payload, stripped out a lot, hope this will be enough: 

1.txt -  this trace is marked as error, it has a span with exception
2.txt -  this one is not marked as erroneous even if it has multiple spans marked as error (a7e7dfa4e383c45f,73249608d24d01f1,034cb330da3ca0eb,3cb3c1e831f54cc3). It also has a span with exception.

[1.txt](https://github.com/opensearch-project/dashboards-observability/files/12228424/1.txt)
[2.txt](https://github.com/opensearch-project/dashboards-observability/files/12228426/2.txt)

**Comment by derek-ho** [comment]
Thanks for raising the issue @anghelyi , I will take a look later today. In the meantime, can you share what you are using - trace analytics with data prepper ingestion agent/looking at jaeger traces, so I can get back to you with a more specific answer?

**Comment by anghelyi** [comment]
Hi Derek! It's not an urgent issue, more like a question to understand how the system works/check if it works correctly on our side. Anyway, we are using open telemetry agents with data prepper. 
Btw, I'll be pretty much offline for the next two weeks, if you need more information or examples I can only provide them after that.

**Comment by anghelyi** [comment]
Hi! Any idea where can I find more information regarding this?

**Comment by Swiddis** [comment]
Hi, so sorry for not getting back! The issue seems to have been buried. I'm looking into it now. Thanks for reaching out and being patient.

So, I'm looking at the [OTEL error handling docs](https://opentelemetry.io/docs/specs/otel/error-handling/), and it looks like correctly identifying errors is the responsibility of the library generating the trace. In particular I'm looking at the line:

> API methods MUST NOT throw unhandled exceptions when used incorrectly by end users.

I don't know much about the setup that's generating these traces, but I do see that in the trace that's not marked as an error, there are stack traces and 500s. That could be related, but no definitive proof.

I also found this [related issue](https://github.com/spring-cloud/spring-cloud-sleuth/issues/2130) from Spring Sleuth, which seems to show up in the stack traces. They mention something about Brave handling it (which I don't see in the stack trace). They also cite Brave's [error handling rationale](https://github.com/openzipkin/brave/blob/master/brave/RATIONALE.md#error-handling) to explain that `error=false` might not actually mean there were no errors:

> When considered in this context, the value of the "error" tag is less important than its existence.

Given this, I'm making a guess that checking for `error=true` is the wrong check to make, which would explain the low error rate.

**Comment by Swiddis** [comment]
Closing as stale
